<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Contact Us_camera-img</name>
   <tag></tag>
   <elementGuidId>c9c2bc85-6bf9-4b16-8ebb-b20eddf59e5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#camera-img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='camera-img']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Cameras&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4211e38d-cdbd-4d6e-bd86-b05c6504654b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../img/camera.svg</value>
      <webElementGuid>1c56a305-7c12-47df-bfb8-bc5187b689a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>camera-img</value>
      <webElementGuid>91447f3d-59fe-4606-89d9-5d1457d833f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;camera-img&quot;)</value>
      <webElementGuid>710c5b4c-df60-4e6e-b101-806d8907d414</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='camera-img']</value>
      <webElementGuid>f8c577ea-306b-4a82-b694-144241705615</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-product1']/div[2]/img</value>
      <webElementGuid>94f33eb5-b654-4f25-a8c3-d63d68ecc0e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a/div/div[2]/img</value>
      <webElementGuid>fde33177-8d21-43ae-b078-6666fcc14391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../img/camera.svg' and @id = 'camera-img']</value>
      <webElementGuid>d3cd72e0-ee1e-4a26-9d7f-ed2ca5bd7074</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
