<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Contact Us_graphic-card</name>
   <tag></tag>
   <elementGuidId>0a893260-2296-4ec4-ba5d-cdc175296356</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#graphic-card</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='graphic-card']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Components&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0f685d45-5cd1-429a-9eda-ec200694e1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../img/cards.svg</value>
      <webElementGuid>3d0bfd28-f8e2-47cb-9f71-e39e74e96dfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>graphic-card</value>
      <webElementGuid>8d6dd771-88c0-41b7-8858-73e6917c569a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;graphic-card&quot;)</value>
      <webElementGuid>ff161c5b-dcbf-44cd-926c-d7db1426f3c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='graphic-card']</value>
      <webElementGuid>7d3e63ff-e6c3-4341-92d9-498b353d4def</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-product5']/div[2]/img</value>
      <webElementGuid>922cef43-b948-42e0-a62c-e7e729d545ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a/div/div[2]/img</value>
      <webElementGuid>d08114b6-13d2-49ee-be94-7f9902c14a94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../img/cards.svg' and @id = 'graphic-card']</value>
      <webElementGuid>4339b7ee-eecc-45ab-8b27-898a386056cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
