<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Contact Us_nintendo</name>
   <tag></tag>
   <elementGuidId>fbc992a9-d19d-42ba-b4f6-7a4f0e200b90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nintendo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='nintendo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Game Consoles&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ef75866a-fd8a-486e-bf56-1de570e39c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../img/nintendo.svg</value>
      <webElementGuid>e1e4a9b9-301e-4f6a-b882-b2e3b717b01d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nintendo</value>
      <webElementGuid>26ecc1a7-605b-4649-82f2-189637b9bd0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nintendo&quot;)</value>
      <webElementGuid>283613de-af36-4a3d-afbd-e5d048d81a7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='nintendo']</value>
      <webElementGuid>d74a43f3-9de0-4e82-ac19-3d19c58410e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-product4']/div[2]/img</value>
      <webElementGuid>714c80ac-e6ea-4648-bafc-68c2b3581827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a/div/div[2]/img</value>
      <webElementGuid>568c2059-f474-4a05-89de-becb0e83fc14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../img/nintendo.svg' and @id = 'nintendo']</value>
      <webElementGuid>592e0682-19fb-4e3e-aff4-7b29db40a23d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
