<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Contact Us_boombox</name>
   <tag></tag>
   <elementGuidId>504c1a9f-bc01-4860-ba5e-d4bac43dc3eb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#boombox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='boombox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Audio&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>99065f2a-a058-42cf-935d-1973fd4a2eca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../img/boombox.svg</value>
      <webElementGuid>ea6587e1-c5a2-4b4c-8606-e0a08548949a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>boombox</value>
      <webElementGuid>e1da86c7-35bd-4b23-a86c-bd393c017a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;boombox&quot;)</value>
      <webElementGuid>8dd907b9-356b-4dce-b0aa-de0b6a045e34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='boombox']</value>
      <webElementGuid>1feb8326-422b-4237-95e6-1cbcf34952dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-product7']/div[2]/img</value>
      <webElementGuid>b444f2e3-1efb-47e2-955b-f2eb64cc5fd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/a/div/div[2]/img</value>
      <webElementGuid>0817d0f0-51a5-4cd7-9878-4d123e1d3f84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../img/boombox.svg' and @id = 'boombox']</value>
      <webElementGuid>73956305-8516-4ab8-8d64-fd96411bc10a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
