<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Contact Us_computer</name>
   <tag></tag>
   <elementGuidId>ecd4a927-6c64-4efb-86f4-5cae3969ac25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#computer</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='computer']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Desktop Systems&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>fb3aa055-c30b-4fcb-9eb4-f27d0fded1a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../img/computer.svg</value>
      <webElementGuid>8a5ed5a5-762b-4466-8c57-daa7f9c9d22c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>computer</value>
      <webElementGuid>d8b3edc0-2b22-4bb8-9fb2-93627b0e20ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;computer&quot;)</value>
      <webElementGuid>18783782-d1b1-45b2-b331-82deebd2bd54</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='computer']</value>
      <webElementGuid>e529be69-4d4f-49c7-8d8e-28dc97dbfc6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-product6']/div[2]/img</value>
      <webElementGuid>4668b26f-05aa-4bc0-a837-047ad375e6a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/a/div/div[2]/img</value>
      <webElementGuid>8b5bee2d-c9b3-445a-93f9-7b021a55a6e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../img/computer.svg' and @id = 'computer']</value>
      <webElementGuid>784cb838-3049-49dd-ade9-43b1e3899e31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
