<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Contact Us_laptop2</name>
   <tag></tag>
   <elementGuidId>a3c399a8-450f-41f3-9638-6c1db9385713</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#laptop2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='laptop2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Used Laptops&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9b949668-b0a8-4c28-9795-4114f3086af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../img/laptop2.svg</value>
      <webElementGuid>f925f4b7-2e71-4be0-abfc-11400c3b2763</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>laptop2</value>
      <webElementGuid>1c6ed29b-f76e-40fe-a581-82df2741f5e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;laptop2&quot;)</value>
      <webElementGuid>5fc7d993-ea03-4f24-a835-a9d207c931c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='laptop2']</value>
      <webElementGuid>625ed3b4-cd72-4ab7-b137-939abf8a9d54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-product3']/div[2]/img</value>
      <webElementGuid>ed4b1f22-9b9d-4f0b-be8c-826b5713b8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/div/div[2]/img</value>
      <webElementGuid>bbf3a693-1f70-4178-94b5-48752cd4803c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../img/laptop2.svg' and @id = 'laptop2']</value>
      <webElementGuid>2c0907f7-6e7b-4777-a4bb-90ab3cbbf117</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
