<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_New Laptops</name>
   <tag></tag>
   <elementGuidId>a1a020a0-3807-41d7-9c75-d9768365cf52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#container-product2 > div.section-title > p.sub-heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container-product2']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;New Laptops&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>3109a6fe-93cb-4997-864c-1bd6cae43827</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-heading</value>
      <webElementGuid>cb5589c2-071c-43cb-87a8-b6da5fda06e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Laptops</value>
      <webElementGuid>912910dc-06cc-4ffc-89ae-32b6bc01cb32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container-product2&quot;)/div[@class=&quot;section-title&quot;]/p[@class=&quot;sub-heading&quot;]</value>
      <webElementGuid>d5f31e15-b97c-41f9-9ec2-632ceb37ab2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-product2']/div/p</value>
      <webElementGuid>f4262aff-812c-4040-9864-7d266fefff13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::p[3]</value>
      <webElementGuid>2bbabd4e-d432-4506-8268-5cfb4dadc3bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Products'])[1]/following::p[3]</value>
      <webElementGuid>f46aef4b-1db6-45ac-a467-a6e1a1caa227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::p[7]</value>
      <webElementGuid>c2a7376b-3caa-4711-b787-e64b5f597156</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New Laptops']/parent::*</value>
      <webElementGuid>0f4a5e95-4047-4a50-af53-f6353a4f46aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/a/div/div/p</value>
      <webElementGuid>f3b9bd8d-622e-4aed-8dcd-03ec74ca85b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'New Laptops' or . = 'New Laptops')]</value>
      <webElementGuid>ebfa4173-1b2d-4a5c-85ca-1cccf3405130</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
