<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Special Offers</name>
   <tag></tag>
   <elementGuidId>e62c5d8b-3aae-4273-9e25-8313e3fff5ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.sub-heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='container-special-offers']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Special Offers&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>977867c2-5f1e-45f3-aef3-9bee2348e554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sub-heading</value>
      <webElementGuid>3c8c8089-5517-45f3-a49f-1dbbee91a193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Special Offers</value>
      <webElementGuid>81e2d3a9-c674-41c1-a6bf-7688a3b6ab0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;container-special-offers&quot;)/div[@class=&quot;section-title&quot;]/p[@class=&quot;sub-heading&quot;]</value>
      <webElementGuid>9be9f617-7863-4bd9-976d-592d49fd0ff4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container-special-offers']/div/p</value>
      <webElementGuid>3b24f9ce-020d-4bcd-bd6d-8845fa6ff967</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::p[1]</value>
      <webElementGuid>aef4d9d3-bd73-4211-88c9-e8723ac26918</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Our Products'])[1]/following::p[1]</value>
      <webElementGuid>6c9fb631-7022-4e56-982f-75613562da7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::p[9]</value>
      <webElementGuid>8054a9ce-f21c-4639-9aff-829df6f46c42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Special Offers']/parent::*</value>
      <webElementGuid>e3820e0c-9af7-4f9f-a6fb-a0bd9d43eee1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>ff5b3024-aa3a-4d26-81a7-943696fe7e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Special Offers' or . = 'Special Offers')]</value>
      <webElementGuid>17554a0f-d62e-4625-bb20-3b8a0289e955</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
