<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Rechercher</name>
   <tag></tag>
   <elementGuidId>83be6052-5940-4d64-81cc-05a96a47475f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.wp-block-search__button.wp-element-button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='submit']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Rechercher&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c07e6623-d108-4539-ab87-3ef1932ba1f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Rechercher</value>
      <webElementGuid>b2548e5b-4917-483b-b923-c6d1ee5c13c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wp-block-search__button wp-element-button</value>
      <webElementGuid>be23fa79-6b25-4422-9c34-40f084c80ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>e312d349-4d6e-498a-b431-7bcd57b4f598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Rechercher</value>
      <webElementGuid>b06771fa-ac49-4118-a88f-02c2844de225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wp--skip-link--target&quot;)/div[@class=&quot;wp-block-group has-global-padding is-layout-constrained wp-container-core-group-is-layout-6 wp-block-group-is-layout-constrained&quot;]/div[@class=&quot;wp-block-columns alignwide is-layout-flex wp-container-core-columns-is-layout-1 wp-block-columns-is-layout-flex&quot;]/div[@class=&quot;wp-block-column is-vertically-aligned-bottom is-layout-flow wp-block-column-is-layout-flow&quot;]/div[@class=&quot;wp-block-group is-layout-flow wp-block-group-is-layout-flow&quot;]/form[@class=&quot;wp-block-search__button-outside wp-block-search__text-button wp-block-search&quot;]/div[@class=&quot;wp-block-search__inside-wrapper&quot;]/button[@class=&quot;wp-block-search__button wp-element-button&quot;]</value>
      <webElementGuid>2641b440-4f95-4ec5-82a8-9ee4c8fc3341</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='submit']</value>
      <webElementGuid>17ec8620-5635-454d-a1cb-55d3ab09481d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='wp--skip-link--target']/div/div/div[2]/div/form/div/button</value>
      <webElementGuid>aef66084-29bc-43db-b229-79161adcbdc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recherche'])[1]/following::button[1]</value>
      <webElementGuid>7fdf543a-da73-4479-9693-de63b4e1e426</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='La page est introuvable'])[1]/following::button[1]</value>
      <webElementGuid>9aacd077-858e-4c68-ab3d-5d19d1b8794b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Rechercher']/parent::*</value>
      <webElementGuid>e113026d-d1d0-4b26-a567-0d12bcb4cef4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>5bbe2e50-c59f-4440-8449-519b9bdf866d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Rechercher' or . = 'Rechercher')]</value>
      <webElementGuid>6d7a2b3e-dd8f-4a36-976a-54614e06ef07</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
