<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_It also has a set of challenges that are _75e8c0</name>
   <tag></tag>
   <elementGuidId>3bb9523a-02a7-4748-ab62-cd2e695d3cb7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(2)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main-content']/div/p[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;It also has a set of challenges that are tracked as you explore and test the API&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>1c741085-f170-431d-b648-5669fd063d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>It also has a set of challenges that are tracked as you explore and test the API.</value>
      <webElementGuid>78b17f14-28bc-4466-a864-ffc85cf2eff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/div[@class=&quot;jumbotron&quot;]/p[2]</value>
      <webElementGuid>745f7b9e-62d7-4709-b7aa-b867c4a43a5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/div/p[2]</value>
      <webElementGuid>7f6efa1d-9994-4ec2-95f1-7e46386f047a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The API Challenges'])[1]/following::p[3]</value>
      <webElementGuid>06855912-4142-44bf-9428-47dfcd957c60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Form'])[1]/following::p[3]</value>
      <webElementGuid>af88f47d-34b4-475e-8e1f-ff527dfd9722</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Use The Heroku Hosted Version'])[1]/preceding::p[2]</value>
      <webElementGuid>0253dea7-783c-42b9-8417-29f23765c0e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='About The Challenges Application'])[1]/preceding::p[3]</value>
      <webElementGuid>0c885612-38d2-4091-9d7a-b7b628a21ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='It also has a set of challenges that are tracked as you explore and test the API.']/parent::*</value>
      <webElementGuid>e99097ad-9943-4c31-99ec-b663c2bb3fc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/p[2]</value>
      <webElementGuid>e7d4046e-7767-4833-b785-1fc6a8ef67b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'It also has a set of challenges that are tracked as you explore and test the API.' or . = 'It also has a set of challenges that are tracked as you explore and test the API.')]</value>
      <webElementGuid>4f119544-539f-4223-ba6e-ce91f7c260ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
