<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Find James  workroom-productions.com</name>
   <tag></tag>
   <elementGuidId>2aa6b3b8-c419-4acd-b498-d45ee5608da5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(5)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='postcontent']/p[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Find James @ workroom-productions.com&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>9347fa79-6a09-42a9-a261-ad7115174c52</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Find James @ workroom-productions.com</value>
      <webElementGuid>1e2145b9-0bf1-4b53-bce3-397abc903622</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postcontent&quot;)/p[5]</value>
      <webElementGuid>a4cd901d-dd97-4aa3-af6f-13c9ad91538b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='postcontent']/p[5]</value>
      <webElementGuid>b488e763-485e-402e-a5b7-3a7a8eb447ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Special Guest: James Lyndsay'])[1]/following::p[1]</value>
      <webElementGuid>03b5ef10-1a2e-40ab-b540-5de6eb70a235</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Patreon supporters'])[1]/following::p[3]</value>
      <webElementGuid>14d7ef0f-3a67-4bc1-88e1-36827080ba58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LinkedIn'])[1]/preceding::p[1]</value>
      <webElementGuid>62a8f9f9-79a3-4da1-89be-d4b1bb70988a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Find James @']/parent::*</value>
      <webElementGuid>1f831d2c-53fe-482d-abeb-10ee54aea6e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[5]</value>
      <webElementGuid>f5177f76-1625-4349-9ea3-5ec9e432e714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Find James @ workroom-productions.com' or . = 'Find James @ workroom-productions.com')]</value>
      <webElementGuid>ad95b555-e621-4d87-a9be-ef1ec79cbe96</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
