<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Subscribe to the show</name>
   <tag></tag>
   <elementGuidId>56c29dfe-2516-4b4e-a867-95d854f12d3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.lead</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='content']/div/div/div[4]/div/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Subscribe to the show:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>a4dea173-7ec3-42d9-b254-d901084aaded</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lead</value>
      <webElementGuid>b505be65-74a7-4f38-8b48-025ad4d931bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subscribe to the show:</value>
      <webElementGuid>958bc07f-2d46-477c-bfba-d89c3d520614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/div[@class=&quot;container main-content&quot;]/div[@class=&quot;jumbotron&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;row text-center&quot;]/span[@class=&quot;lead&quot;]</value>
      <webElementGuid>3959fcea-6b91-4c6b-b7f3-e47023fc3acb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='content']/div/div/div[4]/div/span</value>
      <webElementGuid>655d8194-b6e7-4e5f-8d04-3703a78c2570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watch The Show on YouTube'])[1]/following::span[1]</value>
      <webElementGuid>57979e23-f605-4a87-9939-5bebec089505</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Download and Listen to the show as a podcast'])[1]/following::span[1]</value>
      <webElementGuid>976fad4c-1b41-4d56-988b-550754eef36b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watch on YouTube'])[1]/preceding::span[1]</value>
      <webElementGuid>99c4ab61-eb85-4ef2-8cd3-bd97b49c4e96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Watch on YouTube'])[2]/preceding::span[1]</value>
      <webElementGuid>480f203b-5152-4c5c-9390-0db3733f7e09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Subscribe to the show:']/parent::*</value>
      <webElementGuid>2c538844-9ed8-403a-aeb6-5d2e310b4f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span</value>
      <webElementGuid>5e039845-de9e-4011-9888-fd637ef540ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Subscribe to the show:' or . = 'Subscribe to the show:')]</value>
      <webElementGuid>48e726e0-8857-47f0-8600-f0f3d98c40a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
