<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h4_Its that Easy  Well I think it is</name>
   <tag></tag>
   <elementGuidId>0d062a62-5205-441d-bf7a-f932d6b11d69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h4.modal-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='myModal']/div/div/div/h4</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;It’s that Easy!! Well I think it is.....&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
      <webElementGuid>5077d140-f853-43ad-92ce-a74e176ab6dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-title</value>
      <webElementGuid>58f14eb5-90d7-4991-af2b-b549f754190b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>It’s that Easy!!  Well I think it is.....</value>
      <webElementGuid>20b19536-e606-4fe7-b4cd-a9a13248e247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;myModal&quot;)/div[@class=&quot;modal-dialog modal-md&quot;]/div[@class=&quot;modal-content&quot;]/div[@class=&quot;modal-header&quot;]/h4[@class=&quot;modal-title&quot;]</value>
      <webElementGuid>d94841b3-0da2-44ab-9a12-7e0a78615bd5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='myModal']/div/div/div/h4</value>
      <webElementGuid>34620854-b689-442d-b42d-eb944691656c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::h4[1]</value>
      <webElementGuid>eaa9bf87-3adb-4ba5-ac34-d82af1220851</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript Confirm Box'])[1]/following::h4[1]</value>
      <webElementGuid>a166e607-d31b-4464-b4e0-94a0e3e85de2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='click().'])[1]/preceding::h4[1]</value>
      <webElementGuid>57535fd8-991e-4b15-852b-467ce64751e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(The Selenium development team have spent allot of time developing WebDriver functions etc).'])[1]/preceding::h4[1]</value>
      <webElementGuid>4e81ff85-2696-4e2c-96a8-a8ccf331a118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h4</value>
      <webElementGuid>5f2e19e0-4164-4695-81d9-c45b4e6487a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h4[(text() = 'It’s that Easy!!  Well I think it is.....' or . = 'It’s that Easy!!  Well I think it is.....')]</value>
      <webElementGuid>c0b8a195-4287-4f7f-99b5-cec8869036b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
