<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_CLICK ME_1</name>
   <tag></tag>
   <elementGuidId>8767b29e-21a0-4c71-810a-63ac38bef33a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button4 > p</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button4']/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#button4 >> internal:text=&quot;CLICK ME!&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>5aceef92-40bd-4d93-8abd-205f35711f7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CLICK ME!</value>
      <webElementGuid>b58323e7-655f-48ec-bf06-0d215e17ff53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button4&quot;)/p[1]</value>
      <webElementGuid>a07e3ee1-de24-4369-a8eb-87ad014c1d4b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button4']/p</value>
      <webElementGuid>45a53f88-0e51-409a-8b28-a901ae4556d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript Confirm Box'])[1]/following::p[1]</value>
      <webElementGuid>fafbac84-dfc7-464d-9b5f-9ffde7c66cdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLICK ME!'])[3]/following::p[1]</value>
      <webElementGuid>cd86c409-7e0d-4827-ba71-30916ef775f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::p[3]</value>
      <webElementGuid>4bf43b79-a3bd-4502-b236-e2f33f94fcd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/span/p</value>
      <webElementGuid>38070081-0a69-483b-9ceb-98dee837ec96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'CLICK ME!' or . = 'CLICK ME!')]</value>
      <webElementGuid>e66040cb-d4ff-4fe9-8165-2c548f781a46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='button2']/p</value>
      <webElementGuid>bf721340-3e7c-42d2-9705-9fcbfe1c2130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Modal Popup'])[1]/following::p[1]</value>
      <webElementGuid>b4696945-a2da-445c-ad24-38f15954d469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript Alert'])[1]/following::p[2]</value>
      <webElementGuid>a90b59d0-e8a1-4d57-8ebc-a1da7909065b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ajax Loader'])[1]/preceding::p[1]</value>
      <webElementGuid>7c2e5f0f-c5e2-4ba4-ac5a-1dd395f123eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLICK ME!'])[3]/preceding::p[1]</value>
      <webElementGuid>6197a7dd-35bb-4b53-be65-0c6ea498e3cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/span/p</value>
      <webElementGuid>47d17fca-73f0-4c95-a08a-f4fbae971183</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
