<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CLICK ME_1</name>
   <tag></tag>
   <elementGuidId>6a80d747-aed6-40f1-887d-43fb7ff5b85a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button4</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button4']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#button4</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>58f189b7-d1b7-4f2e-93ac-39b573d8cdc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-lg dropdown-toggle</value>
      <webElementGuid>30ae6f3f-fb25-4df4-a385-d8044b50a4e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5be52759-24b5-4d91-93c0-69f7bd2b3327</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button4</value>
      <webElementGuid>a0646033-aa3f-4183-a61b-2152671d7edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>confirmAlert()</value>
      <webElementGuid>d3867762-7be1-4af5-acd9-bc1d50c608e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CLICK ME!</value>
      <webElementGuid>179d908e-b9ab-4433-8d8f-443afbea953a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button4&quot;)</value>
      <webElementGuid>d06ccb8b-a1e3-4fc1-8344-9d2ff3d8ed68</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button4']</value>
      <webElementGuid>0596a220-a092-4d9e-ab2f-d3adcf791ff8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript Confirm Box'])[1]/following::span[1]</value>
      <webElementGuid>88d4006a-ccfd-443d-9881-37dfc8e3018c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CLICK ME!'])[3]/following::span[1]</value>
      <webElementGuid>01a17bb5-cca1-4b96-af2f-8ce454c77e89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::span[1]</value>
      <webElementGuid>d9502fb4-32b5-44e7-b9ea-eff65950cdf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/span</value>
      <webElementGuid>bf5d92a6-1212-4d50-b775-6ffe86285c7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@type = 'button' and @id = 'button4' and (text() = 'CLICK ME!' or . = 'CLICK ME!')]</value>
      <webElementGuid>81f3ba47-ff9f-4437-a986-9cb414151f57</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
