<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_CONTACT US</name>
   <tag></tag>
   <elementGuidId>0e4f7389-f19d-4239-94cd-94c8723f4c96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2[name=&quot;contactme&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@name='contactme']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;CONTACT US&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>8796ffaf-b8b2-4c8c-a076-4c0192f56c90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contactme</value>
      <webElementGuid>0bd899fd-d830-403a-8e04-a86bbc7ba3f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>section_header</value>
      <webElementGuid>446540fd-58a2-47c1-89af-7714b5fee739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTACT US</value>
      <webElementGuid>b5263047-31f1-46ec-8c92-0b9d7159b5af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contact_me&quot;)/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-12 text-center&quot;]/h2[@class=&quot;section_header&quot;]</value>
      <webElementGuid>53b540f2-10d4-4780-b844-67e7fe0635c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@name='contactme']</value>
      <webElementGuid>eb4b8a90-04c6-4508-b5bf-020f0796b973</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='contact_me']/div/div/div/h2</value>
      <webElementGuid>fd871bc9-aed0-44b6-aafb-a0223ea1bffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WebdriverUniversity.com (New Approach To Learning)'])[1]/following::h2[1]</value>
      <webElementGuid>d7c2dabd-b845-48ae-b135-12e9b8c2e364</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle navigation'])[1]/following::h2[1]</value>
      <webElementGuid>145aedc5-1a03-4fbd-b836-c6514f925129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CONTACT US']/parent::*</value>
      <webElementGuid>76d68c00-2719-4516-ae77-901ed5c4d59a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>68ca992e-eeba-48ac-bb77-c51bba5f49e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@name = 'contactme' and (text() = 'CONTACT US' or . = 'CONTACT US')]</value>
      <webElementGuid>205140dc-7c1f-4f52-8fa6-251062a0d5c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
