<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_ACCORDION  TEXT AFFECTS (APPEAR  DISAPPEAR)</name>
   <tag></tag>
   <elementGuidId>d46bfe62-1ae3-405e-a6e7-f545b5f3475e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='page-object-model']/div/div/h1)[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;ACCORDION &amp; TEXT AFFECTS (APPEAR &amp; DISAPPEAR) Click on one of the accordion panels! Do you see any text? Accordions are great way to toggle between hiding and showing large amount of content; waiting for specific items to appear such as text can be quite tricky! I suggest practising wait commands here!&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>5d4d4fb3-daab-42fb-98f0-1067a32bdfa5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ACCORDION &amp; TEXT AFFECTS (APPEAR &amp; DISAPPEAR)</value>
      <webElementGuid>67264b35-9fd1-45e9-843a-46e3493fc379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-12&quot;]/a[@id=&quot;page-object-model&quot;]/div[@class=&quot;thumbnail&quot;]/div[@class=&quot;section-title&quot;]/h1[1]</value>
      <webElementGuid>25bc249e-3205-4038-a814-695d48833e22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='page-object-model']/div/div/h1)[2]</value>
      <webElementGuid>9c70c827-4bcf-42ec-b7cd-96d4e5a4da5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Design a robust framework which is maintainable and reusable!'])[1]/following::h1[1]</value>
      <webElementGuid>1c1ba7a7-f035-47e8-b246-2025e11d8fb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAGE OBJECT MODEL'])[1]/following::h1[1]</value>
      <webElementGuid>6e73990c-4a78-4236-b4ee-e0d81a68366d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Click on one of the accordion panels! Do you see any text?'])[1]/preceding::h1[1]</value>
      <webElementGuid>2380c351-5ef3-4e77-a55e-a095f877490d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DROPDOWN, CHECKBOXE(S) &amp; RADIO BUTTON(S)'])[1]/preceding::h1[1]</value>
      <webElementGuid>a51440e6-5674-49fe-8498-39f4158ca8f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ACCORDION &amp; TEXT AFFECTS (APPEAR &amp; DISAPPEAR)']/parent::*</value>
      <webElementGuid>fad51c20-2e40-4f0d-a044-bcacabdb9964</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/a/div/div/h1</value>
      <webElementGuid>012ade86-729c-4bef-9164-9ac365e88048</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'ACCORDION &amp; TEXT AFFECTS (APPEAR &amp; DISAPPEAR)' or . = 'ACCORDION &amp; TEXT AFFECTS (APPEAR &amp; DISAPPEAR)')]</value>
      <webElementGuid>2f411d9b-8d51-4861-b184-3bde8ff5e02d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
