<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CLICK ME_1</name>
   <tag></tag>
   <elementGuidId>c56a456a-4475-41b5-9029-bf8630a64d84</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button3']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;CLICK ME!!!&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5d9d0d26-3fcf-47fe-893a-fb13f8513918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-lg dropdown-toggle</value>
      <webElementGuid>03fb10ba-6245-4dac-8abe-b8897db5ead6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>55690c2c-01f6-4bdd-aaf0-443c4d732ce1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button3</value>
      <webElementGuid>55ee353e-e7ee-4596-9e8e-0d5cd0ae4449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>048cf703-c52a-4957-840d-ef1fc68c767d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#myModalMoveClick</value>
      <webElementGuid>cc3c38d6-c995-49b1-9f7f-3f4f5671a626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CLICK ME!!!</value>
      <webElementGuid>2d1dfe42-40af-4d7b-aad1-380040444830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button3&quot;)</value>
      <webElementGuid>d88f6000-6773-41f3-8bf6-4b64cf05525b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button3']</value>
      <webElementGuid>705058cc-5b65-4cff-9a51-5eae2fdf8a81</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action Move &amp; Click.'])[1]/following::span[1]</value>
      <webElementGuid>c15da584-10fa-42cc-bdfe-88a6b5595723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is a jQuery Dialog.'])[1]/preceding::span[1]</value>
      <webElementGuid>5e809483-a1c2-4ead-b5e7-12d607f71a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::span[1]</value>
      <webElementGuid>6a1314b0-240b-4608-a367-dcd09060b64e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CLICK ME!!!']/parent::*</value>
      <webElementGuid>1f2ecfb1-9834-48f3-a1e4-614e7db34fee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/span</value>
      <webElementGuid>04cbbce3-6be8-4f9c-960d-8f960a98c0b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@type = 'button' and @id = 'button3' and (text() = 'CLICK ME!!!' or . = 'CLICK ME!!!')]</value>
      <webElementGuid>429e44fe-5689-4ffe-8b66-0bfe71a2cb46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
