<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_CLICK ME</name>
   <tag></tag>
   <elementGuidId>e8507845-316a-47b0-9cac-aaece9046fda</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#button2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='button2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;CLICK ME!!&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dcce840a-5a57-47a9-8852-88a179ea61b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-default btn-lg dropdown-toggle</value>
      <webElementGuid>bc143a1d-e5e3-4798-9ec5-ba90a5f98daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>71cdbc62-cad4-4361-ba7c-467f093370e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>button2</value>
      <webElementGuid>d0a640dd-a284-4764-a8c8-d9307e6595ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>fff591a5-d6d1-4a97-8ba8-f0f9bacf54c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-target</name>
      <type>Main</type>
      <value>#myModalJSClick</value>
      <webElementGuid>a9d2e711-86d5-4e5c-ac88-69ef0cb2e4d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CLICK ME!!</value>
      <webElementGuid>385048c1-fc38-455d-a3c9-6907b866d491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;button2&quot;)</value>
      <webElementGuid>f666565d-df4f-4763-be74-0600446df481</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//span[@id='button2']</value>
      <webElementGuid>65fd11fe-96e7-4aa8-b865-fd9ddb25171b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JavaScript click.'])[1]/following::span[1]</value>
      <webElementGuid>1acfda7b-ebfa-4830-b77c-c9052e19baab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action Move &amp; Click'])[1]/preceding::span[1]</value>
      <webElementGuid>431e67a5-0164-4c3b-9421-b6f46e94db4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create a WebElement based on the button below.'])[3]/preceding::span[1]</value>
      <webElementGuid>57a0766b-0d19-4b27-a883-61f5a146b1f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CLICK ME!!']/parent::*</value>
      <webElementGuid>6b0d25fe-bd2b-410a-8dc0-b5d064044012</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/span</value>
      <webElementGuid>1becb797-515b-4488-9769-da6a9637838b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@type = 'button' and @id = 'button2' and (text() = 'CLICK ME!!' or . = 'CLICK ME!!')]</value>
      <webElementGuid>f91bf8d7-830e-4548-8703-5be5f4b71f23</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
