<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_TO-DO LIST_plus-icon</name>
   <tag></tag>
   <elementGuidId>89a72f77-5a5e-41f0-be60-743446f1a178</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#plus-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//i[@id='plus-icon']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#plus-icon</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>04197883-9455-448e-b9eb-5213ab79db6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-plus</value>
      <webElementGuid>84107b86-886c-4ea4-a7de-edf78c9c97b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d42f22d8-5768-46d0-b8ff-15c9c1f9aa2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>plus-icon</value>
      <webElementGuid>4ed2331f-8fb9-43d8-a884-e5851fc4c8fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;plus-icon&quot;)</value>
      <webElementGuid>9d9cda47-33f3-4b34-ac5d-4c80fcacc44c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//i[@id='plus-icon']</value>
      <webElementGuid>222c85e6-cc03-4e95-8ce9-8e5ad55595d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='container']/h1/i</value>
      <webElementGuid>171a4e15-caa7-4511-ae94-a85f284cfdfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
      <webElementGuid>349d4024-350a-4426-868c-8bb5da5e291c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//i[@id = 'plus-icon']</value>
      <webElementGuid>a201d1fe-737e-4bb8-a4c5-6db6377cc662</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
