<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_WebdriverUniversity.com (Page Object M_48cfc2</name>
   <tag></tag>
   <elementGuidId>9b764465-5888-4945-a00b-eaaa4da0e820</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.glyphicon.glyphicon-chevron-right</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='carousel-example-generic']/a[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f7389bf2-5838-4c00-962d-063c39dc4ed6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>glyphicon glyphicon-chevron-right</value>
      <webElementGuid>df8826dd-277c-4da3-8ada-d325e8bfb7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;carousel-example-generic&quot;)/a[@class=&quot;right carousel-control&quot;]/span[@class=&quot;glyphicon glyphicon-chevron-right&quot;]</value>
      <webElementGuid>d47c76a8-cfbf-406f-968e-06e126a0ac38</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='carousel-example-generic']/a[2]/span</value>
      <webElementGuid>5e72b56f-eb8e-4cfd-9f41-58290bb04550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span</value>
      <webElementGuid>abdc22d9-f898-4d09-8266-fe488d6489a3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
