<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_1 Entries_1</name>
   <tag></tag>
   <elementGuidId>6ab7388f-c637-4757-a882-a9fbab63bdf1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zone3-entries</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='zone3-entries']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#zone3-entries</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>8f8873e7-6041-42df-88cf-2b80028ddfc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zone3-entries</value>
      <webElementGuid>161f08af-cbd9-450a-97e5-6091f40fdb82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 Entries</value>
      <webElementGuid>f88d6ce1-12c8-4cad-bea5-c2fa2914b19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zone3-entries&quot;)</value>
      <webElementGuid>c7b5bdbe-f80e-48c8-a6bf-27914f3242fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='zone3-entries']</value>
      <webElementGuid>2c880261-e7e9-4233-958a-cb7c26d227b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zone3']/h1</value>
      <webElementGuid>6d45d9a6-0f71-494a-9703-7cb65a9230df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Well done for scrolling to me!'])[1]/following::h1[2]</value>
      <webElementGuid>add278c1-8d60-4e1b-aede-8061efc5c87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Just Scrolling Around!'])[1]/following::h1[2]</value>
      <webElementGuid>961382ee-932b-4558-b11a-ad43d164ef94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dont forget to scroll to me!'])[1]/preceding::h1[1]</value>
      <webElementGuid>7ce4c6d6-49ae-47b0-83b0-122a600408ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::h1[2]</value>
      <webElementGuid>8becd3f5-46dc-4627-8474-35bbd08a57ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/h1</value>
      <webElementGuid>5908f2a3-b663-4778-b813-569d2529b446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'zone3-entries' and (text() = '1 Entries' or . = '1 Entries')]</value>
      <webElementGuid>20c54f05-653b-4f90-8dff-3c57ac4ceb50</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
