<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_1 Entries</name>
   <tag></tag>
   <elementGuidId>9ba69bae-809d-4814-9802-bfadbb887d98</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#zone2-entries</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='zone2-entries']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;1 Entries&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>f1426585-e2ba-4353-af36-a9fb8671966f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>zone2-entries</value>
      <webElementGuid>42761581-b8f7-4f03-8e75-9b4469231be3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1 Entries</value>
      <webElementGuid>34674d8f-8a95-47c3-87e8-8dadb3794133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;zone2-entries&quot;)</value>
      <webElementGuid>d0576f96-0b39-4f1d-8cfe-ceb88561bfac</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='zone2-entries']</value>
      <webElementGuid>01369606-a24e-4a9f-8d02-af0c483928db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='zone2']/h1</value>
      <webElementGuid>c14705b0-6fc8-4528-8f28-3a96101befb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Well done for scrolling to me!'])[1]/following::h1[1]</value>
      <webElementGuid>98f68c83-0b2f-4163-898a-a1daab6b1ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Just Scrolling Around!'])[1]/following::h1[1]</value>
      <webElementGuid>3349cd72-cd8a-4725-bf8c-a7a2105ca914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dont forget to scroll to me!'])[1]/preceding::h1[2]</value>
      <webElementGuid>5431444e-e946-4023-9cbb-46db5e3fdfc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/preceding::h1[3]</value>
      <webElementGuid>35475d9f-04ac-4e7d-a4f1-06a60f922147</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1 Entries']/parent::*</value>
      <webElementGuid>bd541e9d-c5d6-4199-8660-e17712313ddf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/h1</value>
      <webElementGuid>ad846cb8-13be-44a8-a5db-2a203d26ad5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'zone2-entries' and (text() = '1 Entries' or . = '1 Entries')]</value>
      <webElementGuid>eff3961a-7e81-4053-bad7-77d41da802cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
