<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>yt-formatted-string_Subscriptions</name>
   <tag></tag>
   <elementGuidId>e2c3df9f-a476-44a2-a70b-5cdd998f682a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//a[@id='endpoint']/tp-yt-paper-item/yt-formatted-string)[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>tp-yt-paper-item >> internal:has-text=&quot;Subscriptions&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>yt-formatted-string</value>
      <webElementGuid>c364d0f5-689e-4f80-ae2b-5c56682332ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title style-scope ytd-guide-entry-renderer</value>
      <webElementGuid>331b3fb3-6708-4b42-8484-aeddac039037</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subscriptions</value>
      <webElementGuid>dc45204b-a63e-470e-bcd4-e534b4525bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guide-renderer&quot;)/div[@id=&quot;sections&quot;]/ytd-guide-section-renderer[@class=&quot;style-scope ytd-guide-renderer&quot;]/div[@id=&quot;items&quot;]/ytd-guide-entry-renderer[@class=&quot;style-scope ytd-guide-section-renderer&quot;]/a[@id=&quot;endpoint&quot;]/tp-yt-paper-item[@class=&quot;style-scope ytd-guide-entry-renderer&quot;]/yt-formatted-string[@class=&quot;title style-scope ytd-guide-entry-renderer&quot;]</value>
      <webElementGuid>e81c36de-cd0a-44e7-9e5f-fb7bc7470899</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//a[@id='endpoint']/tp-yt-paper-item/yt-formatted-string)[3]</value>
      <webElementGuid>cfef0c19-0e98-4ed6-883b-f2ba66c12290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shorts'])[1]/following::yt-formatted-string[1]</value>
      <webElementGuid>f5537af3-e7d0-4d7e-b897-5f6dab1e8a7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::yt-formatted-string[2]</value>
      <webElementGuid>90aa4295-5f15-4f24-8301-bbd42b48487a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='You'])[1]/preceding::yt-formatted-string[2]</value>
      <webElementGuid>642f633f-fc16-4d51-af4a-3c6010fa2af6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='History'])[1]/preceding::yt-formatted-string[3]</value>
      <webElementGuid>53fca3c6-a521-414c-a6c7-f19e08b13415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Subscriptions']/parent::*</value>
      <webElementGuid>4fa22ccb-f618-43a3-a282-d46ca95a990e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//ytd-guide-entry-renderer[3]/a/tp-yt-paper-item/yt-formatted-string</value>
      <webElementGuid>b09c3c40-7ab8-4b7c-a3fd-bbe7dac75d39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//yt-formatted-string[(text() = 'Subscriptions' or . = 'Subscriptions')]</value>
      <webElementGuid>5069689d-26fd-4f07-8054-af74cef2496f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
