<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_The API Challenges</name>
   <tag></tag>
   <elementGuidId>73c5561c-701c-4865-a86a-f52d8b590a92</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontentstartshere']/div/h1</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;The API Challenges&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>fe7194cc-88b5-4d8f-827d-2c0504849fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The API Challenges</value>
      <webElementGuid>4db44d8f-9209-4397-aef0-7ca8dd9dcee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontentstartshere&quot;)/div[@class=&quot;main-text-content&quot;]/h1[1]</value>
      <webElementGuid>b4370aba-914d-4e7a-a939-44234f714906</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontentstartshere']/div/h1</value>
      <webElementGuid>151adfee-dbca-4a34-88ac-9cef310dc6e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[Download Open API File]'])[2]/following::h1[1]</value>
      <webElementGuid>013e7903-4920-4b99-94f6-b6e05a89f280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mirror API Docs'])[1]/following::h1[1]</value>
      <webElementGuid>03485b1a-928b-488c-a4ba-b2f58fa72207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A learning environment to experiment, explore, and play with API Testing and Tooling'])[1]/preceding::h1[1]</value>
      <webElementGuid>c12b8a83-5b3d-419e-8d8c-6aff2664ecd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A simple functioning API for you to practice API Testing'])[1]/preceding::h1[1]</value>
      <webElementGuid>c016bc40-89de-46d4-b1f8-4a3a066f9d65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='The API Challenges']/parent::*</value>
      <webElementGuid>2e8d43d6-6dba-40e6-aa10-463da5b21ddd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>e761d6e2-f01c-486b-b629-a34340fb932d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[(text() = 'The API Challenges' or . = 'The API Challenges')]</value>
      <webElementGuid>9730b73d-46c4-4c3f-ab64-eafefb58869f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
