<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_A learning environment to experiment, ex_f79695</name>
   <tag></tag>
   <elementGuidId>2b5ab6db-612b-4c8c-9e18-f2e0461cf83d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontentstartshere']/div/h2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=heading[name=&quot;A learning environment to experiment, explore, and play with API Testing and Tooling&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>a884701a-aea9-418a-8432-64de33f52d7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>A learning environment to experiment, explore, and play with API Testing and Tooling</value>
      <webElementGuid>6ddef026-9452-4313-9a42-55fdc4666606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontentstartshere&quot;)/div[@class=&quot;main-text-content&quot;]/h2[1]</value>
      <webElementGuid>c8baff2a-973c-44cc-9f83-f4700779947d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontentstartshere']/div/h2</value>
      <webElementGuid>5f9fbaac-4173-4b6e-ae52-323ad7c19b67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='The API Challenges'])[1]/following::h2[1]</value>
      <webElementGuid>ca1a1ceb-933c-4350-bccb-a55858359c4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[Download Open API File]'])[2]/following::h2[1]</value>
      <webElementGuid>7dab98fd-96ab-4a9f-a176-26eaf6a516b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A simple functioning API for you to practice API Testing'])[1]/preceding::h2[1]</value>
      <webElementGuid>f11aec93-1578-4f19-b988-782350135c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A learning experience based on a full API, with a set of challenges to help you learn API Testing'])[1]/preceding::h2[1]</value>
      <webElementGuid>aac32130-8cca-4521-9745-d54de70b5a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='A learning environment to experiment, explore, and play with API Testing and Tooling']/parent::*</value>
      <webElementGuid>1175b9d4-da71-499b-9ed6-98a2f2aaa90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>2e90872f-43cf-4114-8849-cc1ce398988c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[(text() = 'A learning environment to experiment, explore, and play with API Testing and Tooling' or . = 'A learning environment to experiment, explore, and play with API Testing and Tooling')]</value>
      <webElementGuid>f3488b4e-0cf1-42e2-8703-5d827fc887f3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
