<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LettuceCabbagePumpkin_vegetable</name>
   <tag></tag>
   <elementGuidId>f4a717f2-22f3-4730-8a1a-641fe8f42973</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;vegetable&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='vegetable']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;vegetable&quot;] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5d9bcc6c-28fc-4db5-b800-22fc8d6bd246</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8b601d57-5829-4939-975c-46dcaaecfdb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>vegetable</value>
      <webElementGuid>ce56f895-37d8-4c9b-9f10-85bf12ba633f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>lettuce</value>
      <webElementGuid>28d3478b-351c-4af5-bc81-d4152f56fb1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radio-buttons-selected-disabled&quot;)/input[1]</value>
      <webElementGuid>04f71e7d-e115-42c1-beba-af69026f2528</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='vegetable']</value>
      <webElementGuid>6e8f6b77-1c87-4676-8629-ff803369e47e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='radio-buttons-selected-disabled']/input</value>
      <webElementGuid>7af1e201-3818-4f2c-baf0-e2f2a957a6d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/form/input</value>
      <webElementGuid>20c208c8-0088-4082-a118-44739eacf056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'vegetable']</value>
      <webElementGuid>c4cdba78-cd9d-495b-bfae-b2dcf3e05e62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
