<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Apple                Orange         _4ab006</name>
   <tag></tag>
   <elementGuidId>df89ede2-842c-4ed0-8081-1c75c5a1c041</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fruit-selects</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='fruit-selects']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#fruit-selects</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>aeacc1cf-e60d-4888-ab51-a60ee523bf71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-menu-lists</value>
      <webElementGuid>daf4e24f-2fc7-4b3b-ba0d-05f679abfa80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fruit-selects</value>
      <webElementGuid>97a96bf8-1f51-4763-b9ca-418a6ad834fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Apple
                Orange
                Pear
                Grape
              </value>
      <webElementGuid>1155f0a3-e49a-45b7-b4ca-c93141f85fd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fruit-selects&quot;)</value>
      <webElementGuid>6a15c647-9a45-4e95-be71-ef6874efb4a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='fruit-selects']</value>
      <webElementGuid>63a5e7ce-2a28-40c9-9e95-d13a49fab56d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selected &amp; Disabled'])[1]/following::select[1]</value>
      <webElementGuid>a7cc3a7a-6596-413a-8cee-232a6af802f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/select</value>
      <webElementGuid>9271025e-bacb-4049-bd01-78d767a20f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'fruit-selects' and (text() = '
                Apple
                Orange
                Pear
                Grape
              ' or . = '
                Apple
                Orange
                Pear
                Grape
              ')]</value>
      <webElementGuid>5a63e33c-c768-4a7a-9d6c-9bac19a83a53</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
