<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_JAVA                  C             _4d974b</name>
   <tag></tag>
   <elementGuidId>fb2a4863-6154-40ac-bb8f-904f6336e437</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dropdowm-menu-1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='dropdowm-menu-1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#dropdowm-menu-1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8ba6c640-2a34-419e-9c06-b553b517c43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-menu-lists</value>
      <webElementGuid>7d45969a-0418-4e3a-964e-40c2fe3eef91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>dropdowm-menu-1</value>
      <webElementGuid>e84321f5-4088-4e2c-948c-5757c02e76dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                  JAVA
                  C#
                  Python
                  SQL
                </value>
      <webElementGuid>d0490428-0b61-46a4-93fd-4ac3cfb171c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dropdowm-menu-1&quot;)</value>
      <webElementGuid>b251265a-7e4f-47d6-8e6d-f42828806485</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='dropdowm-menu-1']</value>
      <webElementGuid>054de37f-7de6-4321-8bc0-fbf1c3b5e09f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dropdown Menu(s)'])[1]/following::select[1]</value>
      <webElementGuid>66412f24-3941-4880-abdf-b0a0fddc97f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dropdown Menu(s), Checkboxe(s) &amp; Radio Button(s)'])[1]/following::select[1]</value>
      <webElementGuid>e46333ab-49e0-4990-896d-19bb120385d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Checkboxe(s)'])[1]/preceding::select[3]</value>
      <webElementGuid>73b2f796-7e27-469f-a3f0-284ce0141652</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Option 1'])[1]/preceding::select[3]</value>
      <webElementGuid>faa56108-73bc-42a3-9dc9-b7475273f812</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>d9fef35e-125c-4606-a087-108beb82fe38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'dropdowm-menu-1' and (text() = '
                  JAVA
                  C#
                  Python
                  SQL
                ' or . = '
                  JAVA
                  C#
                  Python
                  SQL
                ')]</value>
      <webElementGuid>84eb75a8-26e5-423a-a349-d93b7066d538</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
