<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_So mentoring because</name>
   <tag></tag>
   <elementGuidId>412d5dd1-beff-44ae-9ba6-00fcf70ef859</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p:nth-of-type(7)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//section[@id='main-content']/p[7]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;So “mentoring” because:&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>454b134a-f5b1-485f-a653-180ab6ff8af2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>So “mentoring” because:</value>
      <webElementGuid>b4a0ebcc-b2b9-49c0-94dc-1787a3866594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main-content&quot;)/p[7]</value>
      <webElementGuid>d716bb14-86c3-4796-b2fc-be48f7748496</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//section[@id='main-content']/p[7]</value>
      <webElementGuid>0428ecf4-f587-4624-abc0-5010fec3a90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Why Mentoring?'])[1]/following::p[5]</value>
      <webElementGuid>b46164c1-064a-48e2-a7f2-f2a49aa9f22e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Learn More On The Patreon Page'])[1]/following::p[5]</value>
      <webElementGuid>2096bd48-f00d-4726-beea-95bcab070f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I will share my experience of learning and implementing testing for over 20+ years'])[1]/preceding::p[1]</value>
      <webElementGuid>af7be295-b0c8-406a-917e-f77767f8ab31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='I will share my experience of programming and Software Development for over 20+ years'])[1]/preceding::p[1]</value>
      <webElementGuid>a5e1e82c-c6a4-4eb0-9cf2-f314c3c838d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='So “mentoring” because:']/parent::*</value>
      <webElementGuid>6404bc2c-92be-4057-9bb0-3191494996c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[7]</value>
      <webElementGuid>c964de09-1d5f-4098-8e13-e5eeb1e810e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'So “mentoring” because:' or . = 'So “mentoring” because:')]</value>
      <webElementGuid>6bf1f89d-9fa4-4c34-bf19-fcae3990a466</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
